monitor: Fix uuid.h includes
Commit e0e7eb08d5d28a952221070a4b50794d63dcc625 tried to fix this, but
missed most of the files concerned.

Without the fix an out-of-tree build (e.g. make distcheck) will throw
errors like this:

  CC       monitor/l2cap.o
../monitor/l2cap.c:41:18: fatal error: uuid.h: No such file or directory
 #include "uuid.h"